---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  echo-server
  namespace: echo-server
  labels:
    app.kubernetes.io/name:  echo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:  echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  echo-server
    spec:
      containers:
      - name:  echo-server
        image: ealen/echo-server:0.6.0
        ports:
        - name: http
          containerPort:  8080
        env:
        - name: PORT
          value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: echo-server
spec:
  selector:
    app.kubernetes.io/name:  echo-server
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http

