apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2023-06-21T09:33:03Z"
  name: oidc-reviewer
  resourceVersion: "87451"
  uid: 8db5f033-2118-426f-8ec0-f0b19d88dba8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:service-account-issuer-discovery
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
