---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  oidc-test-valid
  labels:
    app.kubernetes.io/name:  oidc-test-valid
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:  oidc-test-valid
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  oidc-test-valid
    spec:
      serviceAccountName: oidc-test
      containers:
      - name:  alpine
        image: alpine:3.18
        command: ["/bin/sh", "-c", "--"]
        args:
        - |
          apk add curl
          while true; do sleep 30; done
        volumeMounts:
        - name: echo-server-token
          mountPath: /var/run/secrets/echo-server
      volumes:
      - name: echo-server-token
        projected:
          sources:
          - serviceAccountToken:
              path: token 
              expirationSeconds: 600
              audience: echo-server.echo-server.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  oidc-test-invalid-sa
  labels:
    app.kubernetes.io/name:  oidc-test-invalid-sa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:  oidc-test-invalid-sa
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  oidc-test-invalid-sa
    spec:
      serviceAccountName: default
      containers:
      - name:  alpine
        image: alpine:3.18
        command: ["/bin/sh", "-c", "--"]
        args:
        - |
          apk add curl
          while true; do sleep 30; done
        volumeMounts:
        - name: echo-server-token
          mountPath: /var/run/secrets/echo-server
      volumes:
      - name: echo-server-token
        projected:
          sources:
          - serviceAccountToken:
              path: token 
              expirationSeconds: 600
              audience: echo-server.echo-server.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  oidc-test-invalid-aud
  labels:
    app.kubernetes.io/name:  oidc-test-invalid-aud
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:  oidc-test-invalid-aud
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  oidc-test-invalid-aud
    spec:
      serviceAccountName: oidc-test
      containers:
      - name:  alpine
        image: alpine:3.18
        command: ["/bin/sh", "-c", "--"]
        args:
        - |
          apk add curl
          while true; do sleep 30; done
        volumeMounts:
        - name: echo-server-token
          mountPath: /var/run/secrets/echo-server
      volumes:
      - name: echo-server-token
        projected:
          sources:
          - serviceAccountToken:
              path: token 
              expirationSeconds: 600
              audience: invalid
